version: 2.1

orbs:
  slack: circleci/slack@3.4.2
  sonarcloud: sonarsource/sonarcloud@1.0.1
  
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - slack/notify:
        webhook: "SK8-Real-Gyro-Unity has checked out the code from git"
      - sonarcloud/scan

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
