version: 2.1

orbs:
  slack: circleci/slack@3.4.2
  sonarcloud: sonarsource/sonarcloud@1.0.1
  
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - slack/notify:
        channel: "CTMS09JKC"
        color: "#42e2f4"
        mentions: ""
        message: "SK8-Real-Gyro-Unity has checked out the code from git"
        webhook: "https://hooks.slack.com/services/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"
      - sonarcloud/scan
      - slack/notify:
        channel: "CTMS09JKC"
        color: "#42e2f4"
        mentions: ""
        message: "SK8-Real-Gyro-Unity has passed on Sonar Quality Gates"
        webhook: "https://hooks.slack.com/services/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"

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
