version: 2.1

orbs:
  slack: circleci/slack@1.0.0
  sonarcloud: sonarsource/sonarcloud@1.0.1
  
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: 
          name: "Setup custom environment variables"
          command: |
            echo 'export MY_ENV_VAR="https://hooks.slack.com/services/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"' >> $BASH_ENV
      - slack/notify:
        color: "#42e2f4"
        message: "SK8-Real-Gyro-Unity has checked out the code from git"
      - sonarcloud/scan

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
