version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1
  slack: circleci/slack@3.4.2
  
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - slack/notify:
        channel: 'CTMS09JKC'
        color: '#42e2f4'
        mentions: ''
        message: 'SK8-Real-Gyro-Unity has checkout from git'
        webhook: 'https://hooks.slack.com/services/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'
      - sonarcloud/scan

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
