version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  build:
    docker:
    - image: node:latest
    cmd: ["/bin/bash"]
    steps:
      - checkout
      - sonarcloud/scan

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
