version: 2

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  build:
    machine:

    steps:
      - checkout
      - sonarcloud/scan

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
